### ISSUE TITLE
Notes and fix todo from 21/02/2021 live install

### ISSUE THREAD

**Issue by sugarraysam** [sugarraysam/archsugar#2]
- [x] Run $ pacman -Sy , make sure avoid "u" because mess up kernel modules (dm_mod)
- [x] $ modprobe dm_mod # required for cryptsetup
- [ ] fix {{ bootstrap_disk }}1 -> requires {{ bootstrap_disk }}p1 in certain occasions (check both cases)
- [x] Add instructions to clean disk (dd if=/dev/zero OR /dev/urandom of=/dev/disk)
- [x] Copy install  script from archsugar packer
- [x] Remount /w size 5G (2G not big enough)
- [x] yay not found (only in blackarch)
- [x] Copy archsugar to /usr/local/bin/archsugar
- [x] Make bootstrap & chroot playbooks idempotent (remove "creates:" and other complexities, just overwrite stuff)
- [ ] Why it skipped pacman-keys??

**Comment by sugarraysam** [comment]
- Copy archsugar to /usr/local/bin/archsugar
- Make bootstrap & chroot playbooks idempotent (remove "creates:" and other complexities, just overwrite stuff)
- Why it skipped pacman-keys??
